spring.application.name=RealEstate2

spring.datasource.url=jdbc:postgresql://localhost:5432/re2_app
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable Spring Session JDBC (optional)
spring.session.store-type=none

blockchain.privateKey=${BLOCKCHAIN_PRIVATE_KEY:}
blockchain.rpc=${BLOCKCHAIN_RPC:http://127.0.0.1:8545}
blockchain.contract=${BLOCKCHAIN_CONTRACT:}

